-- liquibase formatted sql

-- changeset a.chervinskiy:1676295698761-1
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM catalog_table
CREATE TABLE "public"."catalog_table" ("product_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(100), "price" FLOAT8, "weight" FLOAT8, CONSTRAINT "catalog_table_pkey" PRIMARY KEY ("product_id"));

-- changeset a.chervinskiy:1676295698761-2
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM catalog_table
ALTER TABLE "public"."catalog_table" ADD CONSTRAINT "catalog_table_pk" UNIQUE ("name");

